import type { Metadata } from "next";
import SideNav from "./page-components/Side-Nav";

export const metadata: Metadata = {
  title: "Discuz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="bg-[#b5c2ca] h-full">
        {/* <div className="flex min-h-screen h-full"> */}
        {/* <SideNav /> */}
        <div className="flex-grow">{children}</div>
        {/* </div> */}
      </body>
    </html>
  );
}
